spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5434/external_db?useUnicode&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true'
    username: external
    password: external_password
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        id:
          new_generator_mappings: true
        temp:
          use_jdbc_metadata_defaults: false
  sql:
    init:
      mode: always
  liquibase:
    change-log: "classpath:/db/changelog/changelog-master.yaml"