version: "3.8"
services:
  central_database:
    image: postgres:latest
    container_name: central
    environment:
      - POSTGRES_USER=central
      - POSTGRES_PASSWORD=central_password
      - POSTGRES_DB=central_db
    volumes:
      - postgres_central_volume_local:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  external_database:
    image: postgres:latest
    container_name: external
    environment:
      - POSTGRES_USER=external
      - POSTGRES_PASSWORD=external_password
      - POSTGRES_DB=external_db
    volumes:
      - postgres_external_volume_local:/var/lib/postgresql/data:rw"
    ports:
      - "5434:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
volumes:
  postgres_central_volume_local:
    external: true
  postgres_external_volume_local:
    external: true